openapi: 3.0.1
info:
  title: Main Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "3500"
paths:
  /addLecturer:
    post:
      operationId: postAddlecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
  /updateExistingLecturer:
    put:
      operationId: putUpdateexistinglecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /deleteLecturerByLecturerID:
    delete:
      operationId: deleteDeletelecturerbylecturerid
      parameters:
      - name: lecturerID
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /createCourse:
    post:
      operationId: postCreatecourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
  /addCourse:
    post:
      operationId: postAddcourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddingCourse'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
  /retrieveLecturerDetailsByID/{lecturerID}:
    get:
      operationId: getRetrievelecturerdetailsbyidLecturerid
      parameters:
      - name: lecturerID
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
  /retrieveAllLecturerInCertainCourse:
    get:
      operationId: getRetrievealllecturerincertaincourse
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
  /retrieveLectureByOfficeNo:
    get:
      operationId: getRetrievelecturebyofficeno
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Lecturer:
      required:
      - courseCode
      - emailAddress
      - faculty
      - gender
      - lecturerID
      - officeNumber
      - qualification
      - status
      - title
      type: object
      properties:
        lecturerID:
          type: string
        emailAddress:
          type: string
        officeNumber:
          type: string
        faculty:
          type: string
        courseCode:
          type: string
        title:
          type: string
          enum:
          - Mr
          - Mrs
          - Miss
        gender:
          type: string
          enum:
          - Other
          - Female
          - Male
        status:
          type: string
          enum:
          - Married
          - Single
        qualification:
          type: string
          enum:
          - Honours
          - pHD
          - Masters
    Course:
      required:
      - courseCatergory
      - courseCode
      - courseDescription
      - courseName
      - courseNqlLevel
      type: object
      properties:
        courseCode:
          type: string
        courseNqlLevel:
          type: string
        courseName:
          type: string
        courseDescription:
          type: string
        courseCatergory:
          type: string
    AddingCourse:
      required:
      - courseCode
      - courseId
      - staffNumber
      type: object
      properties:
        courseId:
          type: string
        staffNumber:
          type: string
        courseCode:
          type: string
